### ISSUE TITLE
Toggle all

### ISSUE THREAD

**Issue by marcaspers** [ypho/soundboard#5]
Hello, I want to speak to the manager. There should be a toggle all button.

**Comment by bart-faber** [comment]
It's opensource boomer. You have to do it!

**Comment by marcaspers** [comment]
Do you know against who you it have?

**Comment by ypho** [comment]
Timebox 1h?

**Comment by marcaspers** [comment]
On your muil

**Comment by bart-faber** [comment]
I don't know doctor!
